### PR TITLE
Lock ring and more...

### PR DESCRIPTION
**Pull request by TadeasPilar**
These improvements include:

- Lock ring to ring to hold plexi in place
- Parts tray with bigger compartments
- 3D printable rings to replace ball bearings
- Easy fill funnel - for fast filling of lots of parts from tape

PS. This PR is to be squashed and hide my endless attempts to make the readme work.

### CODE REVIEW

**Comment by tablatronix** [comment]
Why did you change the compartment slopes from inner to outer ?

**Comment by UnexpectedMaker** [comment]
Hey @TadeasPilar - If you want the commits squashed, you'l need to do that on your side I believe...
https://gist.github.com/longtimeago/f7055aa4c3bba8a62197

Once you are ready, I'll pull it all in, thanks!

**Comment by UnexpectedMaker** [comment]
> Why did you change the compartment slopes from inner to outer ?

Yeah, the idea of the angle of the slope in my design is to make components "come to you" as they rotate. Closer to pick from and easier to get to, especially for tiny components - but that's just my preference :)

There's no harm in having variations!

**Comment by tablatronix** [comment]
It wasn't noted in the pr so I was curious what the functional difference was

**Comment by TadeasPilar** [comment]
> Why did you change the compartment slopes from inner to outer ?

That is a good question. I messed it up :D

**Comment by TadeasPilar** [comment]
> Hey @TadeasPilar - If you want the commits squashed, you'l need to do that on your side I believe...
> https://gist.github.com/longtimeago/f7055aa4c3bba8a62197
> 
> Once you are ready, I'll pull it all in, thanks!

There is usually "Squash and Merge" option when merging a PR. Maybe you have this disabled? I will squash it in my branch.

**Comment by TadeasPilar** [comment]
All fixed. Ready to merge.

**Pull request merged**
